### ISSUE TITLE
"!src game;category" and "!src game;category|sub-category" not returning any information

### ISSUE THREAD

**Issue by ShikenNuggets** [slashinfty/srcom-bot#1]
Every variation of "!src game;category" and "!src game;category|sub-category" I've attempted to pass to the bot have not returned the desired information, or anything at all.

I've tried all of the following variations multiple times (as well as messing with capitalization as appropriate, getting the abbreviation with and without the /, etc) with no success:
```
!src super mario world;all (copied and pasted directly from the examples)
!src /kdl;beat the game|extra mode (also copied from the examples)
!src arkhamcity;any%
!src arkhamcity;any%|pc
!src arkhamcity;any%|easy
!src arkhamcity;any%|pc|easy
!src arkhamcity;hqr
!src Prototype_2;NG+
!src supersoldier;any%
```
Some of those commands are likely malformed but I have no way of determining this. All other bot commands are (usually) responsive and appear to work as intended.

**Comment by slashinfty** [comment]
Fixed with commit [ed4da6c](https://github.com/slashinfty/srcom-bot/commit/ed4da6c6a85311aad60376c854b10cbbca92fb86). Was referencing old query which was to category, not leaderboard.
